woudc/woudc-data-registry

woudc_data_registry/models.py
Updated existing metadata tables.
Implmented instruments and deployments tables.
Added csvs to complete metadata.
=> Numerous Updates

README.md, woudc_data_registry/controller.py, woudc_data_registry/models.py, woudc_data_registry/parser.py, woudc_data_registry/processing.py, woudc_data_registry/registry.py, woudc_data_registry/search.py, woudc_data_registry/tests/data/Brewer229_Daily_SEP2016.493, woudc_data_registry/tests/data/ecsv-space-in-instrument-name.csv
Added:
- crosschecking
- automatic instrument insertion 
- bypass permission option
- ElasticSearch updates
Fixed bugs, logging and tests.
=> Updates and fixes.

README.md, woudc_data_registry/epicentre/contributor.py, woudc_data_registry/epicentre/instrument.py, woudc_data_registry/epicentre/metadata.py, woudc_data_registry/epicentre/station.py, woudc_data_registry/models.py, woudc_data_registry/processing.py, woudc_data_registry/registry.py, woudc_data_registry/search.py
Adds new ElasticSearch indexes and attaches them to processing routine. Adds ElasticSearch handling to model CLI. Introduces the `admin search sync` command, which (attempts to) precisely sync the search index with the registry.
=> ElasticSearch Processing

woudc_data_registry/models.py, woudc_data_registry/processing.py, woudc_data_registry/search.py
=> fix id refs, add station date properties, fix format of prompts

Makefile, README.md, docs/administration.rst, woudc_data_registry/models.py, woudc_data_registry/processing.py, woudc_data_registry/search.py
=> rename admin search CLI, add file output path to data record model

woudc_data_registry/models.py, woudc_data_registry/parser.py, woudc_data_registry/tests/test_data_registry.py
Edits preparation of DataRecord.number_of_observations so that it works without dataset table validation. Adds number_of_observations method to ExtendedCSV class and adds tests.
=> Number of Observations Counting

woudc_data_registry/processing.py
Any variables formerly named "permission" are now "go_ahead_for_*_addition", with * being a placeholder for more text.
=> Permission Variable Names

Makefile, README.md, docs/administration.rst, docs/publishing.rst, woudc_data_registry/models.py, woudc_data_registry/search.py
=> align CLI admin subcommands

docs/administration.rst
See fetch-content.sh location at https://gccode.ssc-spc.gc.ca/woudc/msc-woudc-data-registry/merge_requests/1.
=> Document WMO countries and fetch-content.sh

docs/development.rst
Development documentation for table definitions files.
=> Initial Table Definitions Documentation

.travis.yml, data/extra-options.yml, data/migrate/tables-backfilling.yml, default.env, woudc_data_registry/config.py, woudc_data_registry/epicentre/contributor.py, woudc_data_registry/epicentre/deployment.py, woudc_data_registry/epicentre/instrument.py, woudc_data_registry/epicentre/station.py, woudc_data_registry/processing.py, woudc_data_registry/registry.py, woudc_data_registry/search.py, woudc_data_registry/tests/data/general/ecsv-missing-instrument-name.csv, woudc_data_registry/tests/test_data_registry.py
Added a new file for numerous smaller configuration options. Connect a few of those options to processing and model CLI.
This file is meant for additional options to be added over time, like the configuration file for WOUDC-BPS.
=> Extra Configurations

woudc_data_registry/epicentre/instrument.py, woudc_data_registry/models.py, woudc_data_registry/processing.py, woudc_data_registry/search.py
updated instrument index to include deployment field
=> Instrument Index Update

woudc_data_registry/controller.py, woudc_data_registry/dataset_validators.py, woudc_data_registry/epicentre/notification.py, woudc_data_registry/models.py, woudc_data_registry/parser.py, woudc_data_registry/processing.py
Pull request including interpreter error prevention and bugfixes to the notifications class.
=> WAF ingest bugfix pull request

docs/running.rst, woudc_data_registry/config.py, woudc_data_registry/dataset_validators.py, woudc_data_registry/models.py, woudc_data_registry/peer/__init__.py, woudc_data_registry/peer/eubrewnet.py, woudc_data_registry/registry.py, woudc_data_registry/search.py, woudc_data_registry/util.py
cc @danielwaiforssell @victoriaspada
=> add federated data centre support

woudc_data_registry/models.py
Update PeerDataRecords model to allow station types landFixed and lanOnIce
=> Update PeerDataRecords Model

woudc_data_registry/models.py, woudc_data_registry/peer/eubrewnet.py, woudc_data_registry/peer/file_indices_extractor.py, woudc_data_registry/peer/ndacc.py
PeerDataRecords: Add Agency property to table and ElasticSearch (optional property).
=> PeerDataRecords: Add Agency to table and ES

woudc_data_registry/models.py, woudc_data_registry/search.py
Filled in properties that were recently added properties to models.py to search.py.
=> Add new properties to search.py

woudc_data_registry/models.py, woudc_data_registry/peer/eubrewnet.py, woudc_data_registry/peer/ndacc.py, woudc_data_registry/search.py
Add contributor and GAW URLs to PeerDataRecords model.
=> Add contributor and GAW URLs to PeerDataRecords

woudc_data_registry/search.py
Update properties of Data Records so that received, published, and processed datetime properties are sortable, as needed by the chart on the UI data search page.
=> Make Data Records properties sortable

requirements.txt, woudc_data_registry/models.py, woudc_data_registry/search.py
For contribution model, change field `station_name` to `name`.
=> Change station_name field to name

woudc_data_registry/generate_metadata.py, woudc_data_registry/search.py
Link changes to Discovery Metadata for WOUDC 2.0 UI use.
=> Link changes to Discovery Metadata

woudc_data_registry/models.py
Change chunk sync capacities for sync and product sync to prevent sqlalchemy sessions from crashing.
=> Change chunk sync capacities for sync and product-sync

woudc_data_registry/generate_metadata.py
Small Apostrophe fix in Metadata Generation, in generate_metadata.py
=> Apostrophe fix in Metadata Generation

README.md, woudc_data_registry/epicentre/instrument.py, woudc_data_registry/epicentre/metadata.py, woudc_data_registry/models.py, woudc_data_registry/search.py
- Added `station_dobson_corrections` table to the database
- Added Elasticsearch (ES) index for station corrections
- Cleaned up the code
- Performed test updates
- Updated the instrument add command to correctly get the contributor id and project id from the input.
=> Update wdr setup: Add station_dobson_corrections table and ES index

.gitignore, woudc_data_registry/product/ozonesonde/ozonesonde_generator.py, woudc_data_registry/product/totalozone/totalozone_generator.py, woudc_data_registry/registry.py
- fixed bug for TotalOzone and OzoneSonde Product Generation
- Updated .gitignore
=> Updated the Product Generation

woudc_data_registry/gather.py
Updated gathering command to create folders when unzipping folders from the ftp account.
=> Updated gathering command

README.md, woudc_data_registry/cli_options.py, woudc_data_registry/controller.py, woudc_data_registry/dobson_corrections.py, woudc_data_registry/epicentre/__init__.py, woudc_data_registry/epicentre/contributor.py, woudc_data_registry/epicentre/deployment.py, woudc_data_registry/epicentre/instrument.py, woudc_data_registry/epicentre/notification.py, woudc_data_registry/epicentre/station.py, woudc_data_registry/models.py, woudc_data_registry/notification/__init__.py, woudc_data_registry/peer/eubrewnet.py, woudc_data_registry/peer/ndacc.py, woudc_data_registry/product/ozonesonde/__init__.py, woudc_data_registry/product/uv_index/__init__.py, woudc_data_registry/search.py
=> add CLI verbosity functionality

README.md, woudc_data_registry/epicentre/notification.py, woudc_data_registry/models.py
- Created a click command to convert the db tables to csv files
- Made it so that the csv files can be added to the db using the admin init command
=> Backing up Database

woudc_data_registry/reminders/contributor_reminder.py, woudc_data_registry/util.py
Handled the case where a contributor has not submitted ANY files (could occur if the contributor is new) by checking validation status.
=> Contributor Validation Check
